### ISSUE TITLE
New "invisible" captcha option not working

### ISSUE THREAD

**Issue by Codesesh** [UndefinedOffset/silverstripe-nocaptcha#26]
Hi there,

According to the docs we should be able to use the new "invisible" captcha from google. Is this the case? I have a stackoverflow question started here that has more details: http://stackoverflow.com/questions/43200694/how-to-implement-the-new-invisible-recaptcha-on-form

Cheers,
Kieran

**Comment by UndefinedOffset** [comment]
It should work, make sure your default size is set to invisible. I added support not too long ago, try adding the below in your config also make sure your key is setup for the invisible captcha or you will get an error from the recaptcha api. Let me know if that works. There may not be a tag with support as well at the moment.

```yml
NocaptchaField:
    default_size: "invisible"
```

**Comment by Codesesh** [comment]
@UndefinedOffset - Yip I had gotten an invisible key, I tried a new invisible key and a normal key just before and both show the captcha whilst using `default_size: "invisible"` - no errors came up...

Does it hide the captcha for you?

**This is my _config/config.yml**

```
FormSpamProtectionExtension:
  default_spam_protector: NocaptchaProtector
```

```
NocaptchaField:
  site_key: "InvisibleKeyFromGoogle" #Your site key (required)
  secret_key: "InvisibleKeyFromGoogle" #Your secret key (required)
  verify_ssl: true #Allows you to disable php-curl's SSL peer verification by setting this to false (optional, defaults to true)
  default_theme: "light" #Default theme color (optional, light or dark, defaults to light)
  default_type: "image" #Default captcha type (optional, image or audio, defaults to image)
  default_size: "invisible" #Default size (optional, normal, compact or invisible, defaults to normal)
  proxy_server: "" #Your proxy server address (optional)
  proxy_auth: "" #Your proxy server authentication information (optional)
```
