### ISSUE TITLE
reCaptcha & HTML5 Validation

### ISSUE THREAD

**Issue by LiamW** [UndefinedOffset/silverstripe-nocaptcha#66]
The invisible mode overtakes a button's click and submits the form first without running the HTML5 validation. So the form tries to submit. Yes you can set SS required on the fields, but the page still reloads with errors. Better UX to have HTML5 validation working.

https://stackoverflow.com/questions/44021400/how-to-run-recaptcha-only-if-html5-validation-has-passed/44026198#44026198

**Comment by purplespider** [comment]
I would argue this is more of a bug than an enhancement, as it causes Userforms' javascript validation to be bypassed.

e.g. You have a Userform and have set a field to have a minimum length. If the user has entered fewer characters than required but clicks submit, it briefly says "Please enter at least 10 characters." but submits the form anyway:

![Screenshot 2021-07-09 at 13 38 27](https://user-images.githubusercontent.com/329880/125078966-01e19800-e0bb-11eb-82d8-740d59c04644.gif)

**Comment by UndefinedOffset** [comment]
ya I agree @purplespider  flagged as such

**Comment by UndefinedOffset** [comment]
@LiamW In my local tests (Firefox and Chrome) pure html5 validation is being triggered before the submit event so nocaptcha does not appear to be involved. I'm curious what browser you were using and what mode of recaptcha (invisible, normal, v3)?

@purplespider In my local testing I do see jQuery validate being triggered that said perhaps it's a load order problem. If `userforms.js` is loaded after `NocaptchaField.js` it's possible that it's listeners are not being triggered properly.

Can both of you post what version of userforms you are using (if applicable), nocaptcha, and which version of Silverstripe you are using.

**Comment by UndefinedOffset** [comment]
Also any JS console errors would be helpful

**Comment by purplespider** [comment]
Here's an example: https://nocaptcha.pswd.biz/test-form Try submitting the form with less than 10 characters and see what happens.

This is a fresh Silverstripe 4.8.0 install on PHP 7.4, just with the latest versions of `userforms` and `nocaptcha` installed:
* `"silverstripe/userforms": "^5.9"`
* `"undefinedoffset/silverstripe-nocaptcha": "^2.1"`

**spam.yml:**
````yml
SilverStripe\SpamProtection\Extension\FormSpamProtectionExtension:
    default_spam_protector: UndefinedOffset\NoCaptcha\Forms\NocaptchaProtector
UndefinedOffset\NoCaptcha\Forms\NocaptchaField:
    site_key: "XXXX" #Your site key (required)
    secret_key: "XXXX" #Your secret key (required)
    default_theme: "light" #Default theme color (optional, light or dark, defaults to light)
    default_size: "invisible" #Default size (optional, normal, compact or invisible, defaults to normal)
    default_badge: "bottomright" #Default badge position (bottomright, bottomleft or inline, defaults to bottomright)
````

I then created a user forms page, added a text field and the spam protection field, and set the "Allowed text length" on the text field to "`10` to `1000`".

Not seeing any errors in the console.

---
Here is an example page with a single field set as Required, like @LiamW's experience: https://nocaptcha.pswd.biz/test-required-form

You can see if you submit the form without completing the field, the JS validation error appears, but the form still submits, then the server-side validation error message appears.
